# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2023-07-07T11:17:56+00:00

from __future__ import annotations

from pydantic import BaseModel


class ChatRequest(BaseModel):
    userId: str
    message: str


class ChatResponse(BaseModel):
    message: str
